apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: wordpress-secret
  data:
  - secretKey: mariadb-user
    remoteRef:
      key: Database
      property: user
  - secretKey: mariadb-password
    remoteRef:
      key: Database
      property: password
  - secretKey: mariadb-root-password 
    remoteRef:
      key: Database
      property: root  

  # # metadataPolicy to fetch all the labels in JSON format
  # - secretKey: tags
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo

  # # metadataPolicy to fetch a specific label (dev) from the source secret
  # - secretKey: developer
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo
      # property: dev
